# Generated by Django 2.2.16 on 2022-02-05 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220205_2235'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_together',
        ),
    ]
